name: Teste Automatizado Web - Java
on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        firefox: [ '84.0', 'latest-beta', 'latest-devedition', 'latest-nightly', 'latest-esr', 'latest' ]
    name: Firefox ${{ matrix.firefox }} sample

    steps:
    - name: Baixando o projeto
      uses: actions/checkout@v2
    - name: Configuracao Java 
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'
        cache: maven
    - name: Instalar firefox 
      id: setup-firefox
      uses: browser-actions/setup-firefox@v1
      with:
        firefox-version: ${{ matrix.firefox }}
    - run: |
          echo Installed firefox versions: ${{ steps.setup-firefox.outputs.firefox-version }}
          ${{ steps.setup-firefox.outputs.firefox-path }} --version
    - name: Automacao web
      run: mvn test
