name: Teste Automatizado Web - Java
on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Baixando o projeto
      uses: actions/checkout@v2
    - name: Configuracao Java 
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'
        cache: maven
    - name: Instalar firefox 
      uses: browser-actions/setup-firefox@latest     
    - name: Automacao web
      run: mvn test
