

name: Teste Automatizado Web - Java
on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Configuracao Java 
    - uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'
        cache: maven
    - name: Automacao web
      run: mvn test
